/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CreateOrderInput {
  'paymentMethod' : string,
  'pickupTime' : string,
  'items' : Array<OrderItem>,
}
export interface MenuItem {
  'id' : bigint,
  'name' : string,
  'isAvailable' : boolean,
  'description' : string,
  'category' : string,
  'price' : bigint,
}
export interface OrderItem {
  'quantity' : bigint,
  'itemPrice' : bigint,
  'menuItemId' : bigint,
}
export interface OrderRecord {
  'id' : bigint,
  'status' : string,
  'paymentMethod' : string,
  'userId' : Principal,
  'createdAt' : bigint,
  'totalAmount' : bigint,
  'pickupTime' : string,
  'items' : Array<OrderItem>,
}
export interface UserProfile {
  'name' : string,
  'role' : string,
  'collegeId' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelOrder' : ActorMethod<[bigint], undefined>,
  'createMenuItem' : ActorMethod<[MenuItem], bigint>,
  'editMenuItem' : ActorMethod<[MenuItem], undefined>,
  'getAllMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyOrders' : ActorMethod<[], Array<OrderRecord>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[CreateOrderInput], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, string], undefined>,
  'updatePickupTime' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];